# Generated by Django 4.1.6 on 2023-02-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Teacher Name')),
                ('rank', models.CharField(max_length=50, verbose_name='Teacher Rank')),
            ],
        ),
    ]
